### ISSUE TITLE
config.yml missing

### ISSUE THREAD

**Issue by TheJessieKirk** [Menacho15/BrandBlocker#2]
Hi, I ran this plugin in purpur 1.20.2 2091. The config file does not appear to exist. Can I please know where it would be if it had been created so I can create it manually? Thanks!

**Comment by Menacho15** [comment]
The config file, named config.yml, should appear in a folder called BrandBlocker, inside of the plugins folder. If it didn't appear, try restarting your server. If that doesn't work either, inside of the .jar file of the plugin, you should be able to find the config.yml file. Then you should create a folder called BrandBlocker inside of your plugins folder, and restart so it loads the config correctly.

![imagen](https://github.com/Menacho15/BrandBlocker/assets/69861104/5e1c8ba1-6495-4587-be8f-a7d4aaa07715)

**Comment by TheJessieKirk** [comment]
Worked fine after manual file creation. Thank you!
