### ISSUE TITLE
Doesn't actually kick

### ISSUE THREAD

**Issue by Joeairforce82** [Menacho15/BrandBlocker#3]
It outputs a message in the console that player was kicked for using launcher not on whitelist. However the player does not actually get kicked and doesn't even see/notice anything on their end. Can check what launcher players are using with no issue. Bypass permission has been set to false for everyone. No errors in console from plugin. It just doesn't actually kick anyone. Server is paper 1.20.2

[config.txt](https://github.com/Menacho15/BrandBlocker/files/13697216/config.txt)

**Comment by SlansLP** [comment]
same here! (spigot 1.20.2 btw)

**Comment by Menacho15** [comment]
Updated BrandBlocker to fix kicking in newer versions, I'll update the plugin on Spigot now.

**Comment by Joeairforce82** [comment]
Works great now. Thanks!
