### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by NoSoyDany** [Menacho15/BrandBlocker#5]
hi plugin isnt loading
i've uploaded a video on this URL https://www.youtube.com/watch?v=xvFZjo5PgG0

have a nice day

**Comment by Menacho15** [comment]
🙄 en fin

**Comment by NoSoyDany** [comment]
hi, the problem's not solved

![un perro](https://github.com/user-attachments/assets/c89b386b-91b2-4d3b-affc-f57cbc274c94)
w support

plz help
